#!/bin/lua

dofile("../mods/parade_server/utilities.lua")

function setup_timestamps()
    os.execute("touch -t  01010101 test_files/schem1")
    os.execute("touch -t  01010102 test_files/schem2")
    os.execute("touch -t  01010103 test_files/schem3")
    os.execute("touch -t  01010104 test_files/aa_schem")
end

setup_timestamps()

result_files = unix_listdir("test_files")
expected_files = { "schem1", "schem2", "schem3", "aa_schem" }

assert(#result_files == #expected_files, "FAIL: expected #files " ..#expected_files .. ", actual #files " .. #result_files)

for i, result_filename in pairs(result_files) do
    assert(result_filename == expected_files[i], "FAIL: " .. i .. " " .. result_filename .. " ~= " .. expected_files[i])
end

print("ALL TESTS HAVE PASSED!!!")



