#!/bin/bash

if [[ "$#" -ne 1 ]]; then
    echo "usage:  install_client_with_git_to_linux [path-to-root-of-minetest-files]"
    exit 1
fi

mkdir --parents $1/games
mkdir --parents $1/worlds
mkdir --parents $1/mods

cp -R ../games/mcr_coderdojo $1/games/
 
cp -R ../worlds/Parade_Client_World $1/worlds/

cp -R ../mods/parade_local $1/mods/

echo Files copied to $1.  Please re-start Minetest to play
